---
title: "Creating & Working with Vectors"
author: "Wade Sedgwick"
date: '2022-08-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(palmerpenguins)
```

# Set global options for the rest of the document - set global options and attach packages

## Make some vectors

```{r}
marmots <- c("blue", "green", 4, "yellow")

# Check class
class(marmots)
```

```{r}
pika <- c(12.4, 6.8, 2.9, 8.8, 8.5)
class(pika)

# Scalar multiplier

scalar_pika <- 5.2 * pika

scalar_pika
```

```{r}
bananas <- c(1, 2, 3)
apples <- c(6, 7, 8)

apples + bananas

bananas - apples

# Dot product in R - %*%

bananas %*% apples

```

### Matrices

```{r}
my_values <- seq(from = 1, to = 5)

my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)

my_matrix
```


```{r}
glimpse(penguins)
str(penguins)

```


# A Cool Update

```{r}
vector_1 <- c("Hello", "I'm", "Wade")
vector_2 <- c("Hello", "I'm", "Ed")

my_df <- data.frame(vector_1, vector_2)
my_df
```


